# Generated by Django 6.0 on 2025-12-04 00:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('points', models.IntegerField(default=0, verbose_name='재화 (포인트)')),
                ('tasks_completed', models.IntegerField(default=0, verbose_name='완료한 심부름 수')),
                ('bio', models.TextField(blank=True, verbose_name='간단 소개')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('content', models.TextField(verbose_name='상세 내용')),
                ('reward_points', models.IntegerField(verbose_name='요구 재화(포인트)')),
                ('location', models.CharField(max_length=200, verbose_name='심부름 위치')),
                ('status', models.CharField(choices=[('open', '모집 중'), ('assigned', '진행 중'), ('completed', '완료됨'), ('expired', '마감됨')], default='open', max_length=10, verbose_name='상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('due_date', models.DateTimeField(verbose_name='마감 기한')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='할당된 도우미')),
                ('registrant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_tasks', to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '대기 중'), ('accepted', '수락됨'), ('rejected', '거절됨')], default='pending', max_length=10, verbose_name='지원 상태')),
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='지원 시간')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_tasks', to=settings.AUTH_USER_MODEL, verbose_name='지원자')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.task', verbose_name='심부름 공고')),
            ],
            options={
                'unique_together': {('task', 'applicant')},
            },
        ),
    ]
