# Generated by Django 6.0 on 2025-12-04 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='selected_title',
            field=models.CharField(default='🐣 새내기', max_length=50, verbose_name='선택된 칭호'),
        ),
    ]
