# Generated by Django 6.0 on 2025-12-04 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_taskreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='min_rating_required',
            field=models.IntegerField(choices=[(0, '0점 이상'), (1, '1점 이상'), (2, '2점 이상'), (3, '3점 이상'), (4, '4점 이상'), (5, '5점 이상')], default=0, verbose_name='최소 별점 조건'),
        ),
        migrations.AddField(
            model_name='task',
            name='required_gender',
            field=models.CharField(choices=[('A', '성별 무관'), ('M', '남성'), ('F', '여성')], default='A', max_length=1, verbose_name='필수 성별 조건'),
        ),
        migrations.AlterField(
            model_name='taskreview',
            name='task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='core.task', verbose_name='심부름 공고'),
        ),
    ]
